### ISSUE TITLE
Matches inside filenames

### ISSUE THREAD

**Issue by muescha** [Trott/remark-lint-prohibited-strings#43] opened 2020-04-25 03:03 UTC
i have a search for: `[Ww]word` -> `Word`

i have many matches where there are file or directories names referenced like:
- `word-plugin`
- `plugin-word-other`
- `plugin-word`

i think they are false positives ... but i don't know exactly how to exclude them

**Comment by Trott** [comment] 2020-04-25 04:14
You can use a negative lookahead to exclude matches when `word` has a hyphen on either side. There is a test case in `test.js` for this. It makes sure that `{ yes: 'Gatsby', no: 'gatsby(?!\\-)' }` does not flag strings like `gatsby-specific`.

To modify that to make sure `plugin-gatsby` also is permitted, I think you could do this (although I haven't tested it yet):

```js
`{ yes: 'Gatsby', no: '(?!\\-)gatsby(?!\\-)' }`
```

The regular expression here is sufficiently not-what-the-average-developer-immediately-reaches-for and the use case is probably common enough that this should likely be added to the documentation.  I'll open a PR right now to make the testing a little more robust and add to the documentation.

**Comment by Trott** [comment] 2020-04-25 04:17
FWIW, the strings won't be checked if they are inside code fences or backticks. So 

```markdown
plugin-word will be flagged but `plugin-word` will not
```

**Comment by muescha** [comment] 2020-04-25 04:22
yes the fences are excluded.

but i see also some [word-plugin](/docs/link) the filesnames used without fences :/

**Comment by Trott** [comment] 2020-04-25 04:35
Updated the answer above to be correct. :-D

Does that work for you?  `{ yes: 'Word', no: '(?<!-)word(?!-)' }`

**Comment by muescha** [comment] 2020-04-25 04:40
interesting regex string: `(\.|@[a-z0-9/-]*)?((?<!-)[Gg]atsby\.?[Jj][Ss](?!-))(\.\w)?`

btw: `[a-z0-9/-]` why is there no `A-Z` here?

**Comment by Trott** [comment] 2020-04-25 04:46
> btw: `[a-z0-9/-]` why is there no `A-Z` here?

I think that's a bug. It probably was intended to be case-insensitive. That part of the reg exp makes sure that we skip checking things that are part of an @-mention. So, even though Nodejs prohibits `v8` as a string, it permits it in `@nodejs/v8`. This bug means that the skipping won't work for `@Nodejs./v8` which would be a bug.

**Comment by Trott** [comment] 2020-04-25 04:52
Closed in https://github.com/Trott/remark-lint-prohibited-strings/pull/45 I think, but let me know if that doesn't fix it. (The info is now at the bottom of the README and a couple more test cases were added.)

**Comment by muescha** [comment] 2020-04-25 05:27
it works mostly.

i added a line to my `.remark.js` settings so i can switch and check if there are false positives...

```javascript
.map(val => {val.no =`(?<!-)${val.no}(?!-)`;return val})
```

it seems i have more new edge cases with slashes 🤔 :

this search string `'(\.|@[a-z0-9/-]*)?((?<!-)gatsby(?!-))(\.\w)?'`:

```Markdown
Docs recipe: https://gatsbyjs.org/docs/recipes/pages-layouts#creating-pages-automatically 
                     ~~~~~~

the header at the top is part of gatsbyjs.org’s layout component
                                 ~~~~~~

issue: https://github.com/gatsbyjs/gatsby/issues/14042 
                          ~~~~~~
```

`(\.|@[a-z0-9/-]*)?((?<!-)[Gg]atsby\.?[Jj][Ss](?!-))(\.\w)?`

```markdown
https://github.com/gatsbyjs/gatsby/blob/master/examples/using-gatsby-with-json-yaml/gatsby-node.js
                   ~~~~~~~~
```

**Comment by muescha** [comment] 2020-04-25 05:53
and this also:

```markdown
and the [AskGatsbyJS](https://twitter.com/AskGatsbyJS) Twitter account
            ~~~~~~~~
```
with 
```json
{
  "s": "(\\.|@[a-zA-Z0-9/-]*)?((?<!-)[Gg]atsby\\.?[Jj][Ss](?!-))(\\.\\w)?",
  "c": "AskGatsbyJS"
}
```

**Comment by Trott** [comment] 2020-04-25 06:55
Oh no! It seems the suggestion here breaks the matching on a word boundary.

**Comment by Trott** [comment] 2020-04-25 12:21
So the fix here using the current release would seem to be to explicitly add word boundaries to the configuration:

```javascript
{ yes: 'Gatsby', no: '\\b(?<!-)gatsby(?!-)\\b' }
```

Does that at least achieve the desired linting results for you?

This is sufficiently complicated that the plugin should probably solve it for the end user, so I'll leave this open as a feature request and see about making this less painful.

**Comment by Trott** [comment] 2020-04-25 13:55
I'm trying to imagine an API whose meaning would be obvious.

Here are some ideas I've had. Feedback and additional suggestions are welcome.

```javascript
{ yes: 'Gatsby', no: 'gatsby', ignoreInHyphenation: true }
```

```javascript
{ yes: Gatsby, no: gatsby, ignoreNextTo: '-' }
```

```javascript
{ yes: Gatsby, no: gatsby, ignoreNextTo: ['-'] }
```

Thinking about some sort of boolean `flagAsSubstring` setting, but I think that will be confusing?

None of these are great. I think `ignoreInHyphenation` is the clearest, but I worry that it might mean adding fifteen other `ignoreIn*` possibilities a year from now? Maybe not, though. Nothing else like this is coming to mind so maybe I'm worrying about something that won't happen. I don't know.

**Comment by muescha** [comment] 2020-04-25 14:05
i thinking also about some options.

since there is a breaking change there can be also a change of params

i suggest some different:

and general `options` and each rule can override it.

```json
{
	"options":{
		"ignoreNextTo": ['-','/'],  // before and after
		"ignoreBefore": ['@'],
		"ignoreAfter": ['https://'],
	},
	"rules":{
		{ 
			"no": "gatsby", 
			"yes": "Gatsby",     //use default
		},
		{ 
			"no": "gatsby", 
			"yes": "Gatsby", 
			"options":{
				"ignoreNextTo": ['_'],  // overwrite default
			},
		},
		{ 
			"no": "gatsby", 
			"yes": "Gatsby", 
			"options":{
				"ignoreNextTo": false,  // disable default
			},
		},
	}
}
```

if we speak about options it can be get very fast overengineered

**Comment by Trott** [comment] 2020-04-25 17:30
Maybe we can try that API incrementally to see if we need all of it. I think there's obvious utility to a per-rule `ignoreNextTo`. So let's start with that and then see if there's a need for `ignoreAfter` and ignoreBefore` and/or a need for global settings?

**Comment by muescha** [comment] 2020-04-25 18:39
If there are this new structure (or similar) then this is open to be extendable .

**Comment by Trott** [comment] 2020-04-25 20:19
Minimal `ignoreNextTo` implementation in https://github.com/Trott/remark-lint-prohibited-strings/pull/52.

**Comment by Trott** [comment] 2020-04-25 20:20
> If there are this new structure (or similar) then this is open to be extendable .

Yes, very much so.

**Comment by Trott** [comment] 2020-04-25 23:03
Does the `ignoreNextTo` option introduced in 1.4.0 meet your practical needs? If so, I'd like to close this and add further enhancements as needed. But if it isn't yet a reasonably ergonomic experience, let's expand it a bit.

**Comment by Trott** [comment] 2020-04-26 01:47
I'm going to optimistically close this, but again, comment or re-open if it isn't meeting your needs yet.

**Closed by Trott** 2020-04-26 01:47 UTC
Labels: enhancement
